### PR TITLE
bnsf, txth, txtp, ffmpeg

### PR DESCRIPTION
**Pull request by bnnm**
- Add ADX key [Kashimashi! Girl Meets Girl (PS2)]
- Fix some BNSF [Taiko No Tatsujin: Drum Session! (PS4)]
- Fix interleaved 2ch XBOX-IMA [Fairly OddParents: Breakin' da Rules (Xbox), ShellShock Nam '67 (Xbox)]
- Add interleaved 2ch XBOX-IMA to TXTH/GENH
- Derive ADX keys automatically if only keystring/keycode is provided
- Update libacm to 1.2 and add .WAVC sfx
- Add DERF DPCM decoder [Stupid Invaders (PC)]
- Add ALP IMA decoder [Lego Racers (PC)]
- Fix some .MSA [Konohana Pack: 3tsu no Jikenbo (PS2)]
- Add TXTP command #sN for subsong N (#N still works)
- Add TXTP commands for looping/time (#i #E #lN #fN #dN #F)
  - #i (ignore loop)
  - #E (force end-to-end loop)
  - #lN (force N loops)
  - #fN (fade time)
  - #dN (fade delay)
  - #F (don't fade after N loops and play song end)
- Apply TXTP looping/time config in foobar/winamp/test.exe
- Fix EA-MT looping [SSX3 (PS2)]
- Add .sod Ogg extension [Zone 4 (PC)]
- Fix some EA SCHl .bnk
- Add .utk [The Sims Online (PC), SimCity 4 (PC)]
- Fix bitrate for layered/segemented layouts
- (dev) Swap custom FFmpeg OPUS for custom streamfile IO
- (dev) Remove custom FFmpeg, as custom IO streamfile can be used instead
- Add ADX key [Bakumatsu Renka - Karyuu Kenshiden (PS2)]

### CODE REVIEW

**Comment by NicknineTheEagle** [comment]
Just wanted to say that you've been doing amazing work over the past two years. Thanks to you, vgmstream is well on its way to becoming all-in-one tool for decoding video game audio.
Know that you have my support, I have decent understanding of this stuff, so feel free to ask me for help with coding or figuring out meta formats.

**Comment by bnnm** [comment]
Why, thanks. Your contributions are also very welcome, and other people's too, no matter how small.

**Comment by NicknineTheEagle** [comment]
https://github.com/kode54/vgmstream/blob/master/doc/TXTP.md
At this point, TXTP is more of a wrapper for sound files than a playlist so I think the description should be changed accordingly.

**Comment by bnnm** [comment]
Technically it evolved from an idea I had of "M3U playlists with config and tags", so it isn't too far off. I guess you could say it's TXT"P"lay settings.

**Comment by kode54** [comment]
Crap, I almost forgot this was open. I need to review and merge this.

**Pull request merged**
